
-- Community Messaging System

create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    sender_id uuid references auth.users not null,
    receiver_id uuid references auth.users not null,
    content text not null,
    read boolean default false
);

-- Force add columns if they are missing (in case table existed with different schema)
alter table public.messages add column if not exists sender_id uuid references auth.users not null;
alter table public.messages add column if not exists receiver_id uuid references auth.users not null;
alter table public.messages add column if not exists content text not null;
alter table public.messages add column if not exists read boolean default false;
alter table public.messages add column if not exists created_at timestamp with time zone default timezone('utc'::text, now()) not null;

alter table public.messages enable row level security;

-- Policies (Safe Re-run)
do $$ 
begin
    if not exists (select 1 from pg_policies where policyname = 'Users can read own received messages') then
        create policy "Users can read own received messages" on messages for select using ( auth.uid() = receiver_id );
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Users can read own sent messages') then
        create policy "Users can read own sent messages" on messages for select using ( auth.uid() = sender_id );
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Users can send messages') then
        create policy "Users can send messages" on messages for insert with check ( auth.uid() = sender_id );
    end if;

    if not exists (select 1 from pg_policies where policyname = 'Receivers can update message status') then
        create policy "Receivers can update message status" on messages for update using ( auth.uid() = receiver_id );
    end if;
end $$;
