
-- Create Bookmarks table
create table public.bookmarks (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users not null,
    book_id text not null,
    unique(user_id, book_id) -- Only bookmark once
);

-- RLS
alter table public.bookmarks enable row level security;

create policy "Users can see own bookmarks."
  on bookmarks for select
  using ( auth.uid() = user_id );

create policy "Users can insert own bookmarks."
  on bookmarks for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete own bookmarks."
  on bookmarks for delete
  using ( auth.uid() = user_id );
