
-- 1. Create table to track WHO prays for WHAT
create table public.prayer_interactions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users not null,
    prayer_id uuid references public.prayers not null, -- Fixed: Matched UUID type
    unique(user_id, prayer_id) -- You can only "Pray" once per request (prevents spamming)
);

-- RLS for interactions
alter table public.prayer_interactions enable row level security;

create policy "Users can see own interactions" on prayer_interactions
  for select using (auth.uid() = user_id);

create policy "Users can insert interactions" on prayer_interactions
  for insert with check (auth.uid() = user_id);

-- 2. Add Streak columns to Profiles
alter table public.profiles 
add column if not exists streak integer default 0,
add column if not exists last_active date;

-- 3. (Optional) Simple function to increment streak
-- We can call this via RPC or just update client side for simplicity.
-- Let's stick to client-side updates for now to avoid complex PL/pgSQL for the user.
