
-- Create Daily Examen table
create table public.daily_examens (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users not null,
    content text not null,
    date date default CURRENT_DATE not null, -- One per day logic
    unique(user_id, date)
);

-- RLS (Strict Privacy)
alter table public.daily_examens enable row level security;

create policy "Users can ONLY see their own examens."
  on daily_examens for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own examens."
  on daily_examens for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own examens."
  on daily_examens for update
  using ( auth.uid() = user_id );
